name: Config Entity Source
description: Config entity source plugin for the Translation Management system.
package: Translation Management
core: 8.x
type: module

dependencies:
 - tmgmt:tmgmt
 - drupal:config_translation
 - drupal:block
