tmgmt.translator.settings.file:
  type: mapping
  mapping:
    export_format:
      type: string
      label: Default export format
    allow_override:
      type: boolean
      label: Allow override of export format
    scheme:
      type: string
      label: Stream wrapper scheme
    xliff_processing:
      type: boolean
      label: Xliff HTML processing
